<a href="https://colab.research.google.com/github/Karnis052/ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Numpy benefits
1. Less memory
2. Fast
3. Convinient

In [ ]:
import time
import sys


In [ ]:
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [ ]:
arr = np.arange(1000)
print(arr.size*arr.itemsize)

8000


In [ ]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [ ]:
help zip?


zip accept iterables like list, tuple, set, dictionaries, files. In unordered iterable like set zip pair randomly

In [ ]:
li1 = [1,2,3]
li2 = ['one', 'two', 'three']
zipped =zip(li1,li2)
list(zipped)


[(1, 'one'), (2, 'two'), (3, 'three')]

In [ ]:
li1 = [1,2,3]
li2 = ['one', 'two', 'three']
zipped =zip(li1,li1)
list(zipped)

[(1, 1), (2, 2), (3, 3)]

In [ ]:
# equal length of short iterator
list(zip(range(5), range(10), range(100)))

[(0, 0, 0), (1, 1, 1), (2, 2, 2), (3, 3, 3), (4, 4, 4)]

In [ ]:
sz= 100000
lis1 = range(sz)
lis2 = range(sz)
st = time.time()
adding = [(x+y) for x, y in zip(lis1, lis2)]
print("Time taken by list: ",  (time.time()-st)*1000)

Time taken by list:  16.341209411621094


In [ ]:
a1 = np.arange(sz)
a2 = np.arange(sz)
st = time.time()
addding = a1+a1
print("Time taken by Numpy array: ",  (time.time()-st)*1000)

Time taken by Numpy array:  4.79435920715332


In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array([1,2,3,4,5], dtype =np.float64)

In [ ]:
a.ndim
a.dtype

dtype('float64')

In [ ]:
b= np.array([[2,3],[5,6],[10,12]])

In [ ]:
# print dimention of array
b.ndim

2

In [ ]:
b

array([[ 2,  3],
       [ 5,  6],
       [10, 12]])

In [ ]:
b.shape # print size of each dimention

(3, 2)

In [ ]:
# create a 3*4 list initialize all element  with zero
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((3,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
## arange function is similar to range is list.
# arguments are arange(start, end, step)
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [ ]:
# linspace(start, end, total number) , generate numbers equal to total_number
# Numbers are linearly spaced between start and end
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
# ravel function just flatten an array more than one dimention to single D
# Don't change Dim of original array
print(ones_array.ravel())

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# max() return maximum element of the array
# min() return minimum element of an array
# sum() return summation of all element
print(a.max())
print(a.min())
print(a.sum())

5.0
1.0
15.0


In [ ]:
b

array([[ 2,  3],
       [ 5,  6],
       [10, 12]])

In [ ]:
# axis =0, vertical direction that means column
#axis =1, Horizontal direction that means row

b.sum(axis =0) # summation of each colomn

array([17, 21])

In [ ]:
b.sum(axis =1)

array([ 5, 11, 22])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
# std is a generic function for standard deviation
np.std(a)

1.4142135623730951

In [ ]:
b.shape

(3, 2)

In [ ]:
c = np.array([[10,11],[20,40],[67,39]])
c.shape

(3, 2)

In [ ]:
b

array([[ 2,  3],
       [ 5,  6],
       [10, 12]])

In [ ]:
c

array([[10, 11],
       [20, 40],
       [67, 39]])

In [ ]:
b+c

array([[12, 14],
       [25, 46],
       [77, 51]])

In [ ]:
b-c

array([[ -8,  -8],
       [-15, -34],
       [-57, -27]])

In [ ]:
c/b

array([[5.        , 3.66666667],
       [4.        , 6.66666667],
       [6.7       , 3.25      ]])

In [ ]:
c*b

array([[ 20,  33],
       [100, 240],
       [670, 468]])

In [ ]:
c =c.reshape(2,3)
c

array([[10, 11, 20],
       [40, 67, 39]])

In [ ]:
# for matrix multiplication A(r1*c1)* B(r2,c2), c1 must be equal to r2. c1= r2 and new matrix size will be C(r1,c2)
b.dot(c)

array([[140, 223, 157],
       [290, 457, 334],
       [580, 914, 668]])

In [ ]:
a = np.array([7,-4,0,3,19,57,9,2])

In [ ]:
a[0:4]

array([ 7, -4,  0,  3])

In [ ]:
a[0::2]

array([ 7,  0, 19,  9])

In [ ]:
a[-1:]

array([2])

In [ ]:
b

array([[ 2,  3],
       [ 5,  6],
       [10, 12]])

In [ ]:
b[0:2,1]

array([3, 6])

In [ ]:
b[-1,0:2]

array([10, 12])

In [ ]:
b[:,1]

array([ 3,  6, 12])

In [ ]:
for row in b:
  print(row)

[2 3]
[5 6]
[10 12]


In [ ]:
for row in b:
  for element in row:
    print(element, end=' ')
  print()
  

2 3 
5 6 
10 12 


In [ ]:
for i in range(len(b)):
  for j in range(len(b[i])):
    print(b[i][j], end=' ')
  print()

2 3 
5 6 
10 12 


In [ ]:
b

array([[ 2,  3],
       [ 5,  6],
       [10, 12]])

In [ ]:
# split the array horizontally
np.hsplit(a,4)

[array([ 7, -4]), array([0, 3]), array([19, 57]), array([9, 2])]

In [ ]:
for cell in b.flatten():
  print(cell, end =' ')

2 3 5 6 10 12 

In [ ]:
for cell in np.nditer(b, order='F'):
  print(cell, end =' ')

2 5 10 3 6 12 

In [ ]:
a.shape

(8,)

In [ ]:
np.size(a)

8

In [ ]:
d = np.arange(8)

In [ ]:
for x , y in zip(a,d):
  print(x,y)

7 0
-4 1
0 2
3 3
19 4
57 5
9 6
2 7
